version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=abc
    ports:
      - "127.0.0.1:5431:5431"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
      - .env
    ports:
      - 8001:8001
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db